accounts/urls.py
from django.urls import path
from accounts import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('register/', views.RegisterCreateView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infosite/urls.py
from django.urls import path
from infosite import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomeCarouselPhotoListView.as_view(), name='home'),
    path('about', views.AboutView.as_view(), name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sparta_django_portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from sparta_django_portals import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infosite.urls')),
    path('accounts/', include('accounts.urls')),
    path('hackaton/', include('hackaton.urls')),
    path('opendata/', include('opendata.urls')),

    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hackaton/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField


class HackatonChallenge(models.Model):
    title = models.CharField(max_length=255)
    # TODO turn the slug field to false in production
    slug = models.SlugField(null=True, unique=True)
    text = RichTextField(blank=True, null=True, config_name='awesome_ckeditor')
    challenge_avatar = models.ImageField(upload_to='challenge_avatar', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("hackatonchallenge_details", kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

infosite/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField


class HomeCarouselPhoto(models.Model):
    carousel_photo = models.ImageField(upload_to='carousel_photo', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

infosite/views.py
from django.shortcuts import get_object_or_404, redirect

from infosite.models import HomeCarouselPhoto

from django.urls import reverse_lazy
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)


class HomeCarouselPhotoListView(ListView):
    template_name = 'portal/components/home.html'
    model = HomeCarouselPhoto
    paginate_by = 4

    def get_queryset(self):
        return HomeCarouselPhoto.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class HomeView(TemplateView):
    template_name = 'portal/components/home.html'


class AboutView(TemplateView):
    template_name = 'portal/components/about.html'

infosite/templates/portal/layout/base.html
</body>
</html>

infosite/templates/portal/layout/head.html
<!DOCTYPE html>
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
    <html>
    <head>
        <title>Hack Portal</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
<style>
    body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
    .w3-row-padding img {margin-bottom: 12px}
    /* Set the width of the sidebar to 120px */
    .w3-sidebar {width: 120px;background: #222;}
    /* Add a left margin to the "page content" that matches the width of the sidebar (120px) */
    #main {margin-left: 120px}

    /* Remove margins from "page content" on small screens */
    @media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
<body class="sparta-maroon-2">

infosite/templates/portal/layout/navbar.html
{% url 'home' as home_url %}
{% url 'about' as about_url %}

{% url 'login' as login_url %}
{% url 'logout' as logout_url %}

{% url 'opendata' as opendata_url %}
{% url 'hackatonchallenge_list' as hackatonchallenge_list_url %}



{% load static %}

<style>
    .sparta-navbar{
        background: #400D13;
        color: white;
    }
    .sparta-navbar-image{
        padding: 20px;
    }

    .sparta-navbar-link {
        background-color: #400D13;
        text-decoration: none;
        transition: background-color .5s;
    }

    .sparta-navbar-link:hover {
        background-color: #B0191D;
    }
    .navbar_small{
        color: white;
    }
    .navbar_small_vertical{
        background: #400D13;
    }
    .text_navbar_small{
        background-color: #400D13;
        text-decoration: none;
        margin-right: 100px;
    }
    .text_navbar_small:hover {
        background-color: #B0191D;
    }
    .sparta_button_small{
        background-color: transparent;
        border: none;
        padding: 10px;
        color: white;
    }
    .sparta_button_small:hover{
        border: none;
        background-color: #B0191D;
    }

</style>


<!-- Icon Bar (Sidebar - hidden on small screens) -->
<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center sparta-navbar">
    <!-- Avatar image in top left corner -->
    <img src="{% static 'images/SPARTA Shield.png' %}"  class="sparta-navbar-image" style="width:100%" alt="">

    <a href="{{ home_url }}" class="w3-bar-item  w3-padding-large sparta-navbar-link">
        <p>HOME</p>
    </a>
    <a href="{{ about_url }}" class="w3-bar-item  w3-padding-large sparta-navbar-link">
        <p>ABOUT</p>
    </a>
    <a href="{{ opendata_url }}" class="w3-bar-item  w3-padding-large sparta-navbar-link">
        <p>OPEN DATA</p>
    </a>
    <a href="{{ hackatonchallenge_list_url }}" class="w3-bar-item  w3-padding-large sparta-navbar-link">
        <p>HACKATHON</p>
    </a>

    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <a href="/admin/" class="w3-bar-item  w3-padding-large sparta-navbar-link">
                <p>ADMIN</p>
            </a>
        {% endif %}

        {% if user.is_participant or user.is_superuser %}
            <a href="" class="w3-bar-item  w3-padding-large sparta-navbar-link">
                <p>CREATE TEAM</p>
            </a>
        {% endif %}

        <a href="" class="w3-bar-item  w3-padding-large sparta-navbar-link">
            <p>ACCOUNT</p>
        </a>
        <a href="{{ logout_url }}" class="w3-bar-item  w3-padding-large sparta-navbar-link">
            <p>LOGOUT</p>
        </a>
    {% else %}
        <a href="{{ login_url }}" class="w3-bar-item  w3-padding-large sparta-navbar-link">
            <p>LOGIN</p>
        </a>
    {% endif %}
</nav>

<!-- Navbar on small screens (Hidden on medium and large screens) -->
<div class="w3-top w3-hide-large w3-hide-medium navbar_small" id="myNavbar">

    <div class="w3-bar w3-opacity w3-hover-opacity-off w3-center w3-small">

        <button class="w3-xlarge w3-left sparta_button_small" onclick="openLeftMenu()">&#9776;</button>

        <div class="w3-sidebar w3-bar-block w3-card w3-animate-left navbar_small_vertical" style="display:none" id="leftMenu">

            <button onclick="closeLeftMenu()" class="w3-bar-item w3-large sparta_button_small">Close &times;</button>

            <a href="./?page=home" class="w3-bar-item   text_navbar_small">
                <p>HOME</p>
            </a>
            <a href="./?page=about" class="w3-bar-item text_navbar_small">
                <p>ABOUT</p>
            </a>
            <a href="./?page=challenges" class="w3-bar-item   text_navbar_small">
                <p>CHALLENGES</p>
            </a>
        </div>
    </div>
</div>

<script>
    function openLeftMenu() {
        document.getElementById("leftMenu").style.display = "block";
    }

    function closeLeftMenu() {
        document.getElementById("leftMenu").style.display = "none";
    }
</script>