accounts/urls.py
from django.urls import path
from accounts import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('register/', views.RegisterCreateView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infosite/urls.py
from django.urls import path
from infosite import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.HomeCarouselPhotoListView.as_view(), name='home'),
    path('about', views.AboutView.as_view(), name='about'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sparta_django_portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from sparta_django_portals import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infosite.urls')),
    path('accounts/', include('accounts.urls')),
    path('hackaton/', include('hackaton.urls')),
    path('opendata/', include('opendata.urls')),

    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

infosite/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField


class HomeCarouselPhoto(models.Model):
    carousel_photo = models.ImageField(upload_to='carousel_photo', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

infosite/views.py
from django.shortcuts import get_object_or_404, redirect

from infosite.models import HomeCarouselPhoto

from django.urls import reverse_lazy
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)


class HomeCarouselPhotoListView(ListView):
    template_name = 'portal/components/home.html'
    model = HomeCarouselPhoto
    paginate_by = 4

    def get_queryset(self):
        return HomeCarouselPhoto.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class HomeView(TemplateView):
    template_name = 'portal/components/home.html'


class AboutView(TemplateView):
    template_name = 'portal/components/about.html'

infosite/templates/portal/components/about.html
{% extends 'portal/base.html' %}
{% load static %}
{% block content %}
<style>
    .about_content{
        color: white;
    }
</style>

 <!-- About Section -->
    <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
        <h2 class="w3-text-light-grey">About</h2>
        <hr style="width:200px" class="w3-opacity">
        <p class="about_content">lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
            ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur
            adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
    </div>
{% endblock %}

infosite/templates/portal/components/carousel.html
{% load static %}

<div class="w3-content w3-section" style="max-width:1000px">
    {% for x in homecarouselphoto_list %}
  <img class="mySlides" src="{{x.carousel_photo.url}}" style="width:100%" alt="">
    {% endfor %}
</div>

<script>
    let myIndex = 0;
    carousel();

function carousel() {
    let i;
    const x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}
  x[myIndex-1].style.display = "block";
  setTimeout(carousel, 7000); // Change image every 2 seconds
}
</script>

infosite/templates/portal/components/home.html
{% extends 'portal/base.html' %}
{% load static %}
 {% block content %}
    <style>
        .sparta-header-image{
            padding: 0px;
        }
        header{
            color: white;
        }
    </style>


    <!-- Header/Home -->
    <header class="w3-container w3-padding-32 w3-center w3-padding-top-64" id="home">
        <img src="{% static 'images/SPARTA Logo Burgundy BG.png' %}" alt="" class="w3-image sparta-header-image" width="60%">

        <h1 class="w3-xlarge"> <b>S</b>marter <b>P</b>hilippines through Data <b>A</b>nalytics <b>R</b>&D, <b>T</b>raining and <b>A</b>doption</h1>
    </header>
     {% include 'portal/components/carousel.html' %}


    {% endblock %}