accounts/urls.py
from django.urls import path
from accounts import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('register/', views.RegisterCreateView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opendata/urls.py
from django.urls import path
from opendata import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.LocalGovernmentUnitListView.as_view(), name='opendata'),
    path('<slug:slug>/details', views.LocalGovernmentUnitDetailView.as_view(), name='localgovernmentunit_details'),
    path('list/', views.LocalGovernmentChallengeListView.as_view(), name='localgovernmentchallenge_list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sparta_django_portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from sparta_django_portals import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infosite.urls')),
    path('accounts/', include('accounts.urls')),
    path('hackaton/', include('hackaton.urls')),
    path('opendata/', include('opendata.urls')),

    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_participant = models.BooleanField(default=False)
    is_local_gov_unit = models.BooleanField(default=False)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)


class Participant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, )

    phone = models.CharField(max_length=50)
    gender_choices = {
        ('male', 'male'),
        ('female', 'female'),
    }
    gender = models.CharField(max_length=50, choices=gender_choices, null=True)
    birth_date = models.DateField(blank=True, null=True)
    # Address info
    # TODO Add list of ph province 2/22/2021
    city_province = models.CharField(max_length=100)
    address = models.TextField()
    # other info
    occupation = models.CharField(max_length=100)
    participant_avatar = models.ImageField(upload_to='participant_avatar', blank=True)


class LocalGovUnit(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    # TODO turn the slug field to false in production
    slug = models.SlugField(null=True, unique=True)
    phone = models.CharField(max_length=50)
    # Address info
    region = models.CharField(max_length=100)
    city_province = models.CharField(max_length=100)
    address = models.TextField()
    lgu_avatar = models.ImageField(upload_to='lgu_avatar', blank=True)
    lgu_detail_avatar = models.ImageField(upload_to='lgu_detail_avatar', blank=True)

    def get_absolute_url(self):
        return reverse("localgovernmentunit_details", kwargs={'slug': self.slug})

opendata/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField


class LocalGovernmentChallenge(models.Model):
    localgovernmentunit = models.ForeignKey('accounts.User',
                                            on_delete=models.CASCADE,
                                            related_name='localgovernmentchallenges'
                                            )
    title = models.CharField(max_length=255)
    slug = models.SlugField(null=False, unique=True)
    text = RichTextField(blank=True, null=True, config_name='awesome_ckeditor')
    challenge_avatar = models.ImageField(upload_to='lgu_challenge_avatar', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("localgovernmentChallenge_details", kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

opendata/views.py
from django.shortcuts import get_object_or_404, redirect

from accounts.models import LocalGovUnit
from opendata.models import LocalGovernmentChallenge

from django.urls import reverse_lazy
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)


class LocalGovernmentUnitListView(ListView):
    model = LocalGovUnit
    template_name = 'opendata.html'

    def get_queryset(self):
        return LocalGovUnit.objects.order_by('user__is_active')


class LocalGovernmentUnitDetailView(DetailView):
    model = LocalGovUnit
    template_name = 'local_government_unit_detail_view.html'

    def get_context_data(self, **kwargs):
        context = super(LocalGovernmentUnitDetailView, self).get_context_data(**kwargs)
        context['lgu_challenges'] = LocalGovernmentChallenge.objects.filter(
            published_date__lte=timezone.now()).order_by('-published_date')
        return context


class LocalGovernmentChallengeListView(ListView):
    model = LocalGovernmentChallenge
    template_name = 'local_government_unit_challenge_list_view.html'

    def get_queryset(self):
        return LocalGovernmentChallenge.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

opendata/templates/local_government_unit_challenge_list_view.html
<h1>HELLO LIST</h1>

{% for localgovernmentchallenge in localgovernmentchallenge_list %}
<h1>{{ localgovernmentchallenge.title }}</h1><br>
{% endfor %}

opendata/templates/local_government_unit_detail_view.html
{% extends 'portal/base.html' %}
{% block content %}
    <style>
        .lgu_logo{
            padding: 10px;
        }
    </style>
    <br>
    <br>
    <div class="w3-content w3-text-grey" id="newsandevents">
        <div class="w3-row">
            <div class="w3-col">
                <div class="w3-card-4  w3-white">
                    <div class="w3-row">
                        <div class="w3-col s6">
                            <img src="{{localgovunit.lgu_detail_avatar.url}}" alt="" class="lgu_logo" style="width:100%">
                        </div>
                        <div class="w3-col s6">
                            <h1><b>{{ localgovunit.city_province }}</b></h1>
                            Address: {{ localgovunit.address}}<br>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>





    <style>
        .hack_card{
            height: 485px;
        }
        @media screen and (max-width: 420px) {
            .hack_card{
                height: auto;
            }
        }
    </style>
    <!-- News and Upcoming Events Section -->
    <br>
    <div class="w3-content w3-text-grey" id="newsandevents">
        <h2 class="w3-text-light-grey">Challenges</h2>
        <hr style="width:200px" class="w3-opacity">
        <div class="w3-row">
            {% for challenge in lgu_challenges %}
                {% if localgovunit.user ==  challenge.localgovernmentunit %}
                    <a href="">
                        <div class="w3-col w3-quarter ">
                            <div class="w3-card-4 w3-margin w3-white hack_card">
                                <img src="{{challenge.challenge_avatar.url}}" alt="" style="width:100%">
                                <div class="w3-container">
                                    <h5><b>{{ challenge.title }}}</b></h5>
                                </div>
                                <div class="w3-container">
                                    {{ challenge.text|safe|slice:":250" }}.....
                                </div>
                            </div>
                        </div>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>


{% endblock %}

opendata/templates/local_government_unit_list_view.html
{% load static %}
<style>
    .lgu_logo{
        padding: 10px;
    }
</style>
    <br>
    <br>
    <div class="w3-content w3-text-grey" id="newsandevents">
        <h2 class="w3-text-light-grey">Local Government Unit Challenges</h2>
        <hr style="width:200px" class="w3-opacity">
        <div class="w3-row">

             {% for lgu in localgovunit_list %}
                <a href="{{ lgu.get_absolute_url }}">
                <div class="w3-col w3-quarter">
                    <!-- hackaton challenge entry -->
                    <div class="w3-card-4 w3-margin w3-white">
                        <img src="{{lgu.lgu_avatar.url}}" alt="" class="lgu_logo" style="width:100%">

                        <div class="w3-container">
                            <h5><b>{{ lgu.city_province }}</b></h5>
                        </div>
                    </div>
                </div>
                </a>
            {% endfor %}
        </div>
    </div>

opendata/templates/opendata.html
{% extends 'portal/base.html' %}
{% block content %}
    {% include 'local_government_unit_list_view.html' %}
{% endblock %}